/**
 * Magic Pencil — single-page assembler.
 *
 *   node build.mjs
 *
 * Stitches partials/head.html + nav.html + the sections + footer.html into
 * index.html, concatenates the per-section CSS/JS, and writes a deployable
 * dist/. No bundler, no dependencies.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync, cpSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const P = (...p) => join(ROOT, ...p);
const read = (p) => (existsSync(p) ? readFileSync(p, 'utf8') : '');

/* Order is the page order AND the cascade order. */
const ORDER = ['hero', 'dragons', 'kingdoms', 'spellbook', 'studio', 'cta'];

const section = (name) => {
  const p = P('partials', 'sections', `${name}.html`);
  if (!existsSync(p)) { console.warn(`  ! missing section: ${name}`); return `\n<!-- MISSING: ${name} -->\n`; }
  return read(p).trim();
};

/* ---- page 2: Paper Cinema ---------------------------------------------- */
function subPage(opts) {
  var head = read(P('partials', 'head.html'))
    .replace(/<title>[\s\S]*?<\/title>/, '<title>' + opts.title + '</title>')
    .replace(/(<meta name="description" content=")[^"]*(")/,
      '$1' + opts.desc + '$2')
    .replace('<link rel="stylesheet" href="assets/css/sections.css">',
             '<link rel="stylesheet" href="assets/css/' + opts.css + '">');
  var nav = read(P('partials', 'nav.html'))
    .replace(/href="#(how|dragons|sandbox|kingdoms|spellbook|studio)"/g, 'href="index.html#$1"')
    .replace(/href="#hero"/g, 'href="index.html"');
  var footer = read(P('partials', 'footer.html'))
    .replace(/href="#(how|dragons|sandbox|kingdoms|spellbook|studio|play)"/g, 'href="index.html#$1"')
    .replace(/href="#hero"/g, 'href="index.html"')
    .replace('<script src="assets/js/sections.js" defer></script>', opts.scripts);

  return `<!doctype html>
<html lang="en">
<head>
${head.trim()}
</head>
<body>
${nav.trim()}

<main id="main">
${read(P('partials', opts.body)).trim()}
</main>

${footer.trim()}
</body>
</html>
`;
}

const html = `<!doctype html>
<html lang="en">
<head>
${read(P('partials', 'head.html')).trim()}
</head>
<body>
${read(P('partials', 'nav.html')).trim()}

<main id="main">
${ORDER.map(section).join('\n\n')}
</main>

${read(P('partials', 'footer.html')).trim()}
</body>
</html>
`;
writeFileSync(P('index.html'), html, 'utf8');
console.log(`  ✓ index.html  (${ORDER.length} sections, ${(html.length / 1024).toFixed(1)} kB)`);

const SUBPAGES = [
  {
    file: 'cinema.html', body: 'cinema.html', css: 'cinema.css',
    title: 'Paper Cinema — Magic Pencil: Kingdoms of Paper',
    desc: 'A battle that is actually happening, watched from eight placed cameras. Runs entirely in your browser.',
    scripts: '<script src="assets/js/rig.js" defer></script>\n<script src="assets/js/cinema.js" defer></script>',
  },
  {
    file: 'mirror.html', body: 'mocap.html', css: 'mocap.css',
    title: 'Paper Mirror — Magic Pencil: Kingdoms of Paper',
    desc: 'Stand in front of your webcam and a paper drawing moves exactly as you do. Nothing is uploaded.',
    scripts: '<script src="assets/js/rig.js" defer></script>\n<script type="module" src="assets/js/mocap.js"></script>',
  },
];
for (const sp of SUBPAGES) {
  const out = subPage(sp);
  writeFileSync(P(sp.file), out, 'utf8');
  console.log(`  \u2713 ${sp.file}  (${(out.length / 1024).toFixed(1)} kB)`);
}

for (const [ext, out] of [['css', P('assets', 'css', 'sections.css')], ['js', P('assets', 'js', 'sections.js')]]) {
  const parts = [`/* GENERATED by build.mjs — edit partials/sections/<name>.${ext} instead. */\n`];
  for (const name of ORDER) {
    const p = P('partials', 'sections', `${name}.${ext}`);
    if (!existsSync(p)) continue;
    const body = read(p).trim();
    if (!body || body === '/* none */') continue;
    parts.push(`\n/* ---------- ${name} ---------- */\n${body}\n`);
  }
  const text = parts.join('');
  writeFileSync(out, text, 'utf8');
  console.log(`  ✓ ${out.replace(ROOT + '/', '')}  (${(text.length / 1024).toFixed(1)} kB)`);
}

const DIST = P('dist');
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
copyFileSync(P('index.html'), join(DIST, 'index.html'));
for (const sp of SUBPAGES) copyFileSync(P(sp.file), join(DIST, sp.file));
cpSync(P('assets'), join(DIST, 'assets'), { recursive: true });
for (const f of ['robots.txt', '.nojekyll']) if (existsSync(P(f))) copyFileSync(P(f), join(DIST, f));
console.log('  ✓ dist/  (deployable)\n\nServe with:  python3 -m http.server 4400');
