/**
 * Magic Pencil — single-page assembler.
 *
 *   node build.mjs
 *
 * Stitches partials/head.html + nav.html + the sections + footer.html into
 * index.html, concatenates the per-section CSS/JS, and writes a deployable
 * dist/. No bundler, no dependencies.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync, cpSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const P = (...p) => join(ROOT, ...p);
const read = (p) => (existsSync(p) ? readFileSync(p, 'utf8') : '');

/* Order is the page order AND the cascade order. */
const ORDER = ['hero', 'prologue', 'chronicle', 'armoury', 'dragons', 'spellbook', 'cta'];

const section = (name) => {
  const p = P('partials', 'sections', `${name}.html`);
  if (!existsSync(p)) { console.warn(`  ! missing section: ${name}`); return `\n<!-- MISSING: ${name} -->\n`; }
  return read(p).trim();
};

/* ---------------------------------------------------------------------------
   Mark the narration beats. The Reader needs to know what to say and in what
   order; rather than hand-tagging every paragraph in every chapter, we derive
   it here: each heading becomes a beat and carries its own label, and every
   substantial paragraph after it becomes a beat under that label.
   Anything inside an SVG, a control, or marked data-no-narrate is skipped.
   --------------------------------------------------------------------------- */
function markNarration(doc) {
  let label = '';
  // headings first, so each one can claim the paragraphs that follow it
  doc = doc.replace(/<(h[123])([^>]*)>([\s\S]*?)<\/\1>/g, (m, tag, attrs, inner) => {
    if (/data-(narrate|no-narrate)/.test(attrs)) return m;
    if (/sr-only|aria-hidden|visually-hidden/.test(attrs)) return m;
    const plain = plainText(inner);
    if (!plain) return m;
    label = plain.length > 48 ? plain.slice(0, 48) + '…' : plain;
    return `<${tag}${attrs} data-narrate data-narrate-label="${esc(label)}">${inner}</${tag}>`;
  });
  // then paragraphs, picking up the label of the heading above them
  let current = '';
  doc = doc.replace(/(<h[123][^>]*data-narrate-label="([^"]*)"[^>]*>)|(<p([^>]*)>([\s\S]*?)<\/p>)/g,
    (m, h, hl, pWhole, pAttrs, pInner) => {
      if (h) { current = hl; return m; }
      if (/data-(narrate|no-narrate)/.test(pAttrs)) return m;
      if (/sr-only|aria-hidden|visually-hidden/.test(pAttrs)) return m;
      const plain = plainText(pInner);
      if (plain.length < 60) return m;                 // captions and one-liners stay silent
      return `<p${pAttrs} data-narrate data-narrate-label="${esc(current)}">${pInner}</p>`;
    });
  return doc;
}
/* Labels are spoken and displayed, so they must be real words — decode the
   entities the markup uses for typesetting before escaping for the attribute. */
function plainText(html) {
  return html
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;|&#160;/g, ' ')
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'")
    .replace(/&[a-z]+;|&#\d+;/gi, ' ')
    .replace(/\s+/g, ' ')
    .replace(/\s+([.,;:!?])/g, '$1')
    .trim();
}
function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;'); }

const html = `<!doctype html>
<html lang="en">
<head>
${read(P('partials', 'head.html')).trim()}
</head>
<body>
${read(P('partials', 'nav.html')).trim()}

<main id="main">
${ORDER.map(section).join('\n\n')}
</main>

${read(P('partials', 'footer.html')).trim()}
</body>
</html>
`;

writeFileSync(P('index.html'), markNarration(html), 'utf8');
console.log(`  ✓ index.html  (${ORDER.length} sections, ${(html.length / 1024).toFixed(1)} kB)`);

for (const [ext, out] of [['css', P('assets', 'css', 'sections.css')], ['js', P('assets', 'js', 'sections.js')]]) {
  const parts = [`/* GENERATED by build.mjs — edit partials/sections/<name>.${ext} instead. */\n`];
  for (const name of ORDER) {
    const p = P('partials', 'sections', `${name}.${ext}`);
    if (!existsSync(p)) continue;
    const body = read(p).trim();
    if (!body || body === '/* none */') continue;
    parts.push(`\n/* ---------- ${name} ---------- */\n${body}\n`);
  }
  const text = parts.join('');
  writeFileSync(out, text, 'utf8');
  console.log(`  ✓ ${out.replace(ROOT + '/', '')}  (${(text.length / 1024).toFixed(1)} kB)`);
}

const DIST = P('dist');
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
copyFileSync(P('index.html'), join(DIST, 'index.html'));
cpSync(P('assets'), join(DIST, 'assets'), { recursive: true });
for (const f of ['robots.txt', '.nojekyll']) if (existsSync(P(f))) copyFileSync(P(f), join(DIST, f));
console.log('  ✓ dist/  (deployable)\n\nServe with:  python3 -m http.server 4400');
